development:
  email: 'seller_1294338383_biz@gmail.com'
  secret: 'stumpsecret'
  cert_id: 'TUDGHDHRBDG4Y'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

test:
  email: 'test@example.com'
  secret: 'testsecret'
  cert_id: 'fakecertid'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

production:
  email: 'treasurer@rrsertoma.org'
  secret: 'supersecret'
  cert_id: 'A7VCJGYC5QDT2'
  cert_file: 'paypal_cert.pem'
  url: 'https://www.paypal.com/cgi-bin/webscr?'
