development:
  email: 'seller_1332807429_biz@gmail.com'
  secret: 'stumpsecret'
  cert_id: 'KVTXN4CJU9D5E'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

test:
  email: 'test@example.com'
  secret: 'testsecret'
  cert_id: 'fakecertid'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

production:
  email: 'treasurer@rrsertoma.org'
  secret: 'supersecret'
  cert_id: 'EJVAVU5U8KU4C'
  cert_file: 'paypal_cert.pem'
  url: 'https://www.paypal.com/cgi-bin/webscr?'
