development:
  email: 'sertoma.test@test.com'
  secret: 'stumpsecret'
  cert_id: 'NSLNRXTJ3U7SC'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

staging:
  email: 'sertoma.test@test.com'
  secret: 'stumpsecret'
  cert_id: 'NSLNRXTJ3U7SC'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

test:
  email: 'test@example.com'
  secret: 'testsecret'
  cert_id: 'fakecertid'
  cert_file: 'paypal_cert_development.pem'
  url: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'

production:
  email: 'treasurer@rrsertoma.org'
  secret: 'supersecret'
  cert_id: 'R84RBJYJMWZNA'
  cert_file: 'paypal_cert.pem'
  url: 'https://www.paypal.com/cgi-bin/webscr?'